### ISSUE TITLE
How can I pass parameters?

### ISSUE THREAD

**Issue by vladkras** [strapi/strapi-generate-new#1]
Sometimes (when you use bash or docker) It's very awkward to use interactive interface for subsequent questions like database name, database host, etc.

Also I can't put database.json to config dir because project root must be empty.

Is it possible to pass database parameters on project creation, say

`strapi new projectName --client=mongo --host=localhost ...`

**Comment by jmchza** [comment]
@vladkras  have you ever got a response on this one ?
I have the same issue given that the lates version does not work for some reason within the container creation.

we will all really appreciate a much clearer guide for creation and deploy of the admin console.
Fingers crossed it is only out of date and they release soon a new one.

Cheers

**Comment by vladkras** [comment]
@jmchza, no, but I've found this: https://github.com/strapi/strapi-docker
